### ISSUE TITLE
Question on how to implement mappings on MM button

### ISSUE THREAD

**Issue by Mike-Lin-UK** [apocatarsis/Naga_KeypadMapper#12]
Is there a way to add mappings to the Scroll Rocker, I.E. the left and right tilt response on the middle mouse button?

**Comment by Destroyer** [comment]
(on naga 2014) left and right wheel is impossible to map because of this issue http://unix.stackexchange.com/questions/231890/same-scancodes-how-to-differ guess it'd need kernel patching

**Comment by Mike-Lin-UK** [comment]
Thanks, Is there a way to utilize the "\" key, this is the output from the program
xdo_send_keysequence_window reported an error for string '\'
Error: Invalid key sequence '\'
Failure converting key sequence '\' to keycodes

**Comment by apocatarsis** [comment]
Oh man I did not know about the tilt issue, that is a same. Maybe in your mouse the tilt buttons happend to have different codes. If that is the case you could simply do it, I believe it is explained in the README.
As for the Backslash thing, you can put every key compatible with xdotool. Here is the complete list: http://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h
It would be "backslash" for the \ symbol I think. You have a conversation about this in here: 
https://github.com/apocatarsis/Naga_KeypadMapper/issues/10
Thank you!

**Comment by apocatarsis** [comment]
As for the Backslash thing, you can put every key compatible with xdotool. Here is the complete list: http://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h
It would be "backslash" for the \ symbol I think. You have a conversation about this in here: 
https://github.com/apocatarsis/Naga_KeypadMapper/issues/10
Thank you!

**Comment by Mike-Lin-UK** [comment]
Thank you
