### ISSUE TITLE
Using .bash_profile for start at login

### ISSUE THREAD

**Issue by apocatarsis** [apocatarsis/Naga_KeypadMapper#15]
I believe the naga.desktop thing only works in Ubuntu, and it has always been a little unpredictable. Using .bash_profile should be better and work wherever bash is used, but adding a line to .bash_profile could be a problem if someone tries, for example, to install several times. 

The current master uses .bash_profile

**Comment by Destroyer** [comment]
I don't think it's better at all, in fact I think it's worse to use since most of the people will use it on ubuntu. Just because  .bash_profile  is not even called in ubuntu see http://askubuntu.com/a/121075/401490

**Comment by apocatarsis** [comment]
Oh I didnt know about the Ubuntu thing. But .profile appears to be more general? Let's drop the .bash_profile then for now

**Comment by apocatarsis** [comment]
Thing is that at least for me, in CentOS or Ubuntu, the autostart has never really worked out of the box...

**Comment by Destroyer** [comment]
Interesting, it always worked for me at least. But either way we can keep the autostart optional and use ~/.profile instead, but first can you try if it works for you?
