### ISSUE TITLE
Middle mouse on a key

### ISSUE THREAD

**Issue by Eluinhost** [apocatarsis/Naga_KeypadMapper#23]
How do you bind middle mouse to a key correctly?

My mappings have `1 - click=2` but the usage seems a little buggy, pressing will start the scroll and with middle mouse pressing it again will stop the scroll but the key will just restart the scroll. Also it will 'bug out' the middle mouse making it 'locked on' causing tabs to be closed when clicking them instead of opening, fixes by using the regular middle mouse.

**Comment by Destroyer** [comment]
Ok, I think I found the problem. If you check the commit you can see what change I've made. I think xdotool poorly handles active window and somehow it gets broken. Hopefully it's gonna work for you. Let me know.

**Comment by Destroyer** [comment]
Fix added in 569d5334524d8290c7dfe4dbc0f878a69d6be232

**Comment by Eluinhost** [comment]
That seems to fix it, thank you very much :)
