### ISSUE TITLE
Ownership of .naga

### ISSUE THREAD

**Issue by felipeacsi** [apocatarsis/Naga_KeypadMapper#26]
Hello

I'm getting an error with chown when I try to install from master. Something like `chown: invalid group: «username:username»`. The change that trigger the error was introduced in https://github.com/apocatarsis/Naga_KeypadMapper/commit/d65b795d3f1787f85cc02411a4478aebc2928a23#diff-3fbb47e318cd8802bd325e7da9aaabe8.

I think the solution could be to replace `+chown -R ${SUDO_USER}:${SUDO_USER} "$HOME"/.naga/` with `+chown -R ${SUDO_USER} "$HOME"/.naga/`. I'm not too sure to make a pull request but that works for me.

**Comment by Destroyer** [comment]
It works, but that wouldn't change the group from root to yours. I don't know how manjaro works in this case but I'd still prefer to change both user and group - does this work for you?
`chown -R ${SUDO_USER}:$(id -gn $SUDO_USER) "$HOME"/.naga/`

**Comment by felipeacsi** [comment]
Yes, that works. Thank you.
