### ISSUE TITLE
Running nagastart.sh shows Invalid Format 0 & unable to grep

### ISSUE THREAD

**Issue by Zyian** [apocatarsis/Naga_KeypadMapper#28]
I'm running Fedora 24 and trying to run the install.sh gives me the following Error:

`[zyian@localhost Naga_KeypadMapper-master] $ sudo bash install.sh`
 `[sudo] password for zyian:`
`grep: /home/zyian/.profile: No such file or directory`
`Adding user zyian to group razer`
`[zyian@localhost Naga_KeypadMapper-master] $ sudo ./nagastart.sh`
`sudo: ./nagastart.sh: command not found`
`[zyian@localhost Naga_KeypadMapper-master] $ ls`
`install.sh      mapping_02.txt  naga.desktop  README.md`
`mapping_01.txt  mapping_03.txt  nagastart.sh  src`
`[zyian@localhost Naga_KeypadMapper-master] $ sudo ./nagastart.sh`
`Invalid format 0`
`./nagastart.sh: line 19: naga: command not found`
`[zyian@localhost Naga_KeypadMapper-master] $ cd /usr/local/bin`
`[zyian@localhost bin] $ ls`
`naga  nagastart.sh`
`[zyian@localhost bin] $ ./nagastart.sh `
`Invalid format 0`
`No naga devices found or you don't have permission to access them.`
`[zyian@localhost bin] $ sudo ./nagastart.sh `
`Invalid format 0`
`./nagastart.sh: line 19: naga: command not found`

**Comment by Destroyer** [comment]
I've never used fedora so I have no idea what's different
```
[zyian@localhost Naga_KeypadMapper-master] $ sudo bash install.sh
[sudo] password for zyian:
grep: /home/zyian/.profile: No such file or directory
```
this is ok


---
sudo ./nagastart.sh  - you should start it from /usr/local/bin as you did afterwards
Invalid format 0, not sure if something changed with xinput, needs investigation.

---
```
./nagastart.sh
Invalid format 0
No naga devices found or you don't have permission to access them.
```

this is the right message... u can try 
check what "files" your naga uses https://github.com/apocatarsis/Naga_KeypadMapper/blob/master/src/naga.cpp#L36..L42
then `cd /dev/input/by-id` and see if those events have read permissions

**Comment by Zyian** [comment]
Thanks, after playing around with it, it partially works
