### ISSUE TITLE
100% CPU usage when Naga is disconnected

### ISSUE THREAD

**Issue by Destroyer** [apocatarsis/Naga_KeypadMapper#7]
If you disconnect naga when the daemon is running, you gonna get 100% CPU usage. 
One of the possible fixes is to close it when naga is disconnected, others would be to just wait until it's connected. 

So for people who are using this on laptop e.g. here's simple fix, however definitely not the best solution surely.

    rd = read (fd, ev, size * 64);
    if (rd == -1)
    exit(1);

**Comment by apocatarsis** [comment]
You are totally right!
I added your fix to the code.

Thank you very much!
