### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by Fl0ux** [apocatarsis/Naga_KeypadMapper#70]
First of all, thanks for your work !

I am testing your tool in WoW Classic and I have spotted an input lag problem when you press several keys at the same time.

Example : 
I am walking pressing the "z" key (I have an azerty keyboard) and at the same time I am casting a spell binded to the key "2" of my Naga Trinity, which correspond to the macro "ctrl+shift+2". While doing this, the game is stuttering. Its is still fluid if do it manually (z + ctrl+shift+2).

**Comment by Fl0ux** [comment]
I did some more tests and it comes out that the lag come from this command :
`xdotool key --window getactivewindow ctrl+shift+2`
Is there anything I can do ?

**Comment by RaulPPelaez** [comment]
if the lag comes from spawning that process externally of the mapper (say in a terminal) then this code does not really have control over it...
You could try to remove the "--window getactivewindow" which I guess might not be necessary if you are running in full screen mode. Maybe checking for the active window is the issue.
If that is not the issue and just calling xdotool causes lag it would be necessary to drop xdotool entirely to fix it. I do not how how to emulate the key presses without it.
Maybe spawning a new xdotool process each time a key is pressed is the issue. That might be solved by interfacing directly with libxdo. 
Do you have some small reproducible test case? 
Is just wow lagging or is the entire system?

**Comment by Fl0ux** [comment]
After more tests, the real problem is the one described in the first post. Pressing multiple key at the same time will freeze the system for a short period (like 0,5 second).
It could be related to the driver itself, more tests to do.

**Comment by Fl0ux** [comment]
I am closing this issue, my problem is not related to your script. Sorry about that.
