### ISSUE TITLE
Buttons on the top of the naga

### ISSUE THREAD

**Issue by Destroyer** [apocatarsis/Naga_KeypadMapper#8]
How about them? Can you keybind them? I mean xfce can't see them but xev can, this program doesn't configure them, do you use something else to make them work or you don't have those keybinded?

**Comment by apocatarsis** [comment]
I think the back/forward buttons are assigned to the mouse device, not the keyboard one. So I do not know how to configure them without messing with the RMB/LMB and the wheel. Surely not with my idea.

**Comment by Destroyer** [comment]
I've tried it and it seems to work. I didn't know how to do it with select so I've done it with threads instead, don't think it's a good idea in terms of performance but it works. 
In order to fix some issues with it I was forced to run this command  `xinput set-button-map 15 1 2 3 4 5 6 7 11 10 8 9 13 14 15`. Basically, it fixes some issues with other apps detecting those extra buttons like chrome and ff (back and forward). This should prevent it from happening while my code should be able to read them.

I've also made some other changes to the code, like running the executable without the path, you can run it only with sudo ./naga 2014   or  epic

Let me know if you find a bug or improvement  https://gist.github.com/Destroyer/24c0584e43f2edb78b93
:)

**Comment by apocatarsis** [comment]
Wow this is very nice!. Thank you!

**Comment by Destroyer** [comment]
Edited script because of naga 2014... looks ugly
https://gist.github.com/Destroyer/6e06984183e8bfbec9a2

**Comment by apocatarsis** [comment]
Thanks for your help Destroyer, you seem to have many good ideas to improve the keymapper, so I added you as a collaborator. Now you can edit in the code directly.
I also created a new branch (testlab) where you can add anything you want. When we check that it works, we will merge it with the master.
The script looks good, I will check later if it works with the epic.

Let me now if you have any problems.

**Comment by Destroyer** [comment]
Thanks, updated version pushed, hopefully it's stable

**Comment by apocatarsis** [comment]
Another one closed!
